export const publicRoutes = [
  "/",
  "/signup",
  "/login",
  "/verify-email",
  "/auth/confirm",
  "/auth/callback",
  "/error",
  "/forgot-password",
  "/reset-password",
  "/pricing",
  "/catalog",
  "/categories",
  "/designers",
];
